# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - saga

before_install: -R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
afterr_install: R -q -e 'tic::after_install()'
script: R -q -e 'tic::script()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
    provider: script
    script: R -q -e 'tic::deploy()'
    on:
      branches: master
      condition:
         - $TRAVIS_PULL_REQUEST = false
         - $TRAVIS_EVENT_TYPE != cron

after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
after_success: R -q -e 'tic::after_success()'
